"""Initial migration

Revision ID: 218589d74919
Revises: 
Create Date: 2024-11-21 09:27:17.833568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218589d74919'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_id'), 'counter', ['id'], unique=False)
    op.create_table('noid',
    sa.Column('noid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False, comment='Type of the NOID, e.g., manifest, canvas'),
    sa.Column('schema', sa.String(), nullable=False, comment="Scheme prefix for the NOID, e.g., 'ark:/'"),
    sa.Column('naan', sa.String(), nullable=False, comment='NAAN (Name Assigning Authority Number) for the NOID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Time when the NOID was created'),
    sa.PrimaryKeyConstraint('noid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noid')
    op.drop_index(op.f('ix_counter_id'), table_name='counter')
    op.drop_table('counter')
    # ### end Alembic commands ###
