"""remove the type column

Revision ID: 6b7be0abe7fe
Revises: 218589d74919
Create Date: 2024-11-21 10:58:20.313738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7be0abe7fe'
down_revision: Union[str, None] = '218589d74919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noid', sa.Column('schema_', sa.String(), nullable=False, comment="Scheme prefix for the NOID, e.g., 'ark:/'"))
    op.drop_column('noid', 'schema')
    op.drop_column('noid', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noid', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Type of the NOID, e.g., manifest, canvas'))
    op.add_column('noid', sa.Column('schema', sa.VARCHAR(), autoincrement=False, nullable=False, comment="Scheme prefix for the NOID, e.g., 'ark:/'"))
    op.drop_column('noid', 'schema_')
    # ### end Alembic commands ###
